bcm-2xxx-rpi: discard lib32 building for rpi-bootfiles
Issue: LINCD-5386

These files rpi-bootfiles, rpi-config and rpi-cmdline are only compiled for
lib64 instead of lib32 just like u-boot, to avoid below building failure:

ERROR: The recipe lib32-rpi-bootfiles is trying to install files into a shared area when those files already exist.
Those files and their manifest location are:
TOPDIR/tmp-glibc/deploy/images/bcm-2xxx-rpi4/bcm2835-bootfiles/start_x.elf
(matched in manifest-bcm_2xxx_rpi4-rpi-bootfiles.deploy)
TOPDIR/tmp-glibc/deploy/images/bcm-2xxx-rpi4/bcm2835-bootfiles/start4.elf
(matched in manifest-bcm_2xxx_rpi4-rpi-bootfiles.deploy)

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>