u-boot bbappend: fix ostree image crash on qemu boot
Add CONFIG_PREBOOT to workaround issue after u-boot upgrade

In order to fix ostree image crash on RPi4 after u-boot upgrade [1],
we remove fdtcontroladdr set in u-boot-uenv [2].

But while booting on qemu, [2] caused ostree image crash
...
Flattened Device Tree blob at 40000000
   Booting using the fdt blob at 0x40000000
ERROR: FDT image overlaps OS image (OS=0x40080000..0x412d5000)
...

So add fdtcontroladdr set back for qemu boot, it will not affect rpi4
boot

[1] https://github.com/u-boot/u-boot/commit/b8fd54d62f92658cbd20ca051304e13eabf24ddd
[2] http://lxgit.wrs.com/cgit/layers/wr-ostree.git/commit/?h=master-wr&id=848cf0136a22797e6068c14ff7c52d17d70e1352

Issue: LINCD-3630

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>